DATABASE_URL = "postgresql+asyncpg://postgres.iskkwnpfyfejpmbbqacf:Sin%6772290@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?ssl=require&prepared_statement_cache_size=0"
NAVER_AD_ACCESS_LICENSE = "01000000007b5035c1e24ff74dc332e62a9278b1cdb30fed08ac1d0e4604cb885b38be44d0"
NAVER_AD_SECRET_KEY = "AQAAAAAASZqncvQadVMh8AZdw3iLvwmlN+nMq+9T2AK+nFWa7Q=="
NAVER_AD_CUSTOMER_ID = "4348120"